insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '390', 'CIVIL ENG. DESIGN PROJECT   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '469', 'GEO-ENVIRONMENTAL ENGINEER. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '390', 'CIVIL ENG. DESIGN PROJECT   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '469', 'GEO-ENVIRONMENTAL ENGINEER. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '244', 'PROGRAMMING METHODOLOGY II  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '312', 'DIGITAL SYSTEMS DESIGN      ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '352', 'DATA STRUCTURES & ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '390', 'CIVIL ENG. DESIGN PROJECT   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '469', 'GEO-ENVIRONMENTAL ENGINEER. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '244', 'PROGRAMMING METHODOLOGY II  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '312', 'DIGITAL SYSTEMS DESIGN      ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '352', 'DATA STRUCTURES & ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '107', 'COMP SCI INDUS EXPERIENCE I ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '207', 'COMP SCI INDUS EXPERIENCE II', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '228', 'SYSTEM HARDWARE             ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '233', 'PROB. & STATS. FOR COMP. SC.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '248', 'OBJ-ORIENTED PROGRAMMING I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '249', 'OBJ-ORIENTED PROGRAMMING II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '335', 'INTRO/THEORETICAL COMP SCI  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '346', 'OPERATING SYSTEMS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '348', 'PRIN./PROGRAMMING LANGUAGES ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '352', 'DATA STRUCTURES + ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '353', 'DATABASES                   ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '354', 'SOFTWARE ENGINEERING I      ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '371', 'COMPUTER GRAPHICS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '490', 'COMPUTER SCIENCE PROJECT I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '492', 'COMPUTER SCIENCE PROJECT II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '390', 'CIVIL ENG. DESIGN PROJECT   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '469', 'GEO-ENVIRONMENTAL ENGINEER. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '244', 'PROGRAMMING METHODOLOGY II  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '312', 'DIGITAL SYSTEMS DESIGN      ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '352', 'DATA STRUCTURES & ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '107', 'COMP SCI INDUS EXPERIENCE I ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '207', 'COMP SCI INDUS EXPERIENCE II', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '228', 'SYSTEM HARDWARE             ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '233', 'PROB. & STATS. FOR COMP. SC.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '248', 'OBJ-ORIENTED PROGRAMMING I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '249', 'OBJ-ORIENTED PROGRAMMING II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '335', 'INTRO/THEORETICAL COMP SCI  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '346', 'OPERATING SYSTEMS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '348', 'PRIN./PROGRAMMING LANGUAGES ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '352', 'DATA STRUCTURES + ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '353', 'DATABASES                   ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '354', 'SOFTWARE ENGINEERING I      ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '371', 'COMPUTER GRAPHICS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '490', 'COMPUTER SCIENCE PROJECT I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '492', 'COMPUTER SCIENCE PROJECT II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '100', 'COOP WORK TERM 1 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '200', 'COOP WORK TERM 2 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '300', 'COOP WORK TERM 3 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '400', 'COOP WORK TERM 4 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '390', 'CIVIL ENG. DESIGN PROJECT   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '469', 'GEO-ENVIRONMENTAL ENGINEER. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '244', 'PROGRAMMING METHODOLOGY II  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '312', 'DIGITAL SYSTEMS DESIGN      ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '352', 'DATA STRUCTURES & ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '107', 'COMP SCI INDUS EXPERIENCE I ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '207', 'COMP SCI INDUS EXPERIENCE II', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '228', 'SYSTEM HARDWARE             ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '233', 'PROB. & STATS. FOR COMP. SC.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '248', 'OBJ-ORIENTED PROGRAMMING I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '249', 'OBJ-ORIENTED PROGRAMMING II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '335', 'INTRO/THEORETICAL COMP SCI  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '346', 'OPERATING SYSTEMS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '348', 'PRIN./PROGRAMMING LANGUAGES ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '352', 'DATA STRUCTURES + ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '353', 'DATABASES                   ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '354', 'SOFTWARE ENGINEERING I      ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '371', 'COMPUTER GRAPHICS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '490', 'COMPUTER SCIENCE PROJECT I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '492', 'COMPUTER SCIENCE PROJECT II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '100', 'COOP WORK TERM 1 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '200', 'COOP WORK TERM 2 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '300', 'COOP WORK TERM 3 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '400', 'COOP WORK TERM 4 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '100', 'COOP WORK TERM 1 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '200', 'COOP WORK TERM 2 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '300', 'COOP WORK TERM 3 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '400', 'COOP WORK TERM 4 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '390', 'CIVIL ENG. DESIGN PROJECT   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '469', 'GEO-ENVIRONMENTAL ENGINEER. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '244', 'PROGRAMMING METHODOLOGY II  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '312', 'DIGITAL SYSTEMS DESIGN      ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '352', 'DATA STRUCTURES & ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '107', 'COMP SCI INDUS EXPERIENCE I ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '207', 'COMP SCI INDUS EXPERIENCE II', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '228', 'SYSTEM HARDWARE             ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '233', 'PROB. & STATS. FOR COMP. SC.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '248', 'OBJ-ORIENTED PROGRAMMING I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '249', 'OBJ-ORIENTED PROGRAMMING II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '335', 'INTRO/THEORETICAL COMP SCI  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '346', 'OPERATING SYSTEMS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '348', 'PRIN./PROGRAMMING LANGUAGES ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '352', 'DATA STRUCTURES + ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '353', 'DATABASES                   ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '354', 'SOFTWARE ENGINEERING I      ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '371', 'COMPUTER GRAPHICS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '490', 'COMPUTER SCIENCE PROJECT I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '492', 'COMPUTER SCIENCE PROJECT II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '100', 'COOP WORK TERM 1 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '200', 'COOP WORK TERM 2 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '300', 'COOP WORK TERM 3 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '400', 'COOP WORK TERM 4 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '100', 'COOP WORK TERM 1 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '200', 'COOP WORK TERM 2 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '300', 'COOP WORK TERM 3 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '400', 'COOP WORK TERM 4 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '251', 'FUNDMNTL/APPLI ELECTROMAGNET', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '264', 'SIGNALS AND SYSTEMS I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '275', 'PRINCIPLES OF ELEC. ENGG.   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '311', 'ELECTRONICS I               ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '364', 'SIGNALS AND SYSTEMS II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '370', 'MODEL+ANALYSIS/PHYS.SYSTEMS ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '425', 'OPT.DEV.  H S COMMUNICATIONS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '433', 'POWER ELECTRONICS           ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '442', 'DIGITAL SIGNAL PROCESSING   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '462', 'DIGITAL TRANSMISSION SYSTEMS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '390', 'CIVIL ENG. DESIGN PROJECT   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '469', 'GEO-ENVIRONMENTAL ENGINEER. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '244', 'PROGRAMMING METHODOLOGY II  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '312', 'DIGITAL SYSTEMS DESIGN      ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '352', 'DATA STRUCTURES & ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '107', 'COMP SCI INDUS EXPERIENCE I ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '207', 'COMP SCI INDUS EXPERIENCE II', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '228', 'SYSTEM HARDWARE             ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '233', 'PROB. & STATS. FOR COMP. SC.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '248', 'OBJ-ORIENTED PROGRAMMING I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '249', 'OBJ-ORIENTED PROGRAMMING II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '335', 'INTRO/THEORETICAL COMP SCI  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '346', 'OPERATING SYSTEMS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '348', 'PRIN./PROGRAMMING LANGUAGES ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '352', 'DATA STRUCTURES + ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '353', 'DATABASES                   ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '354', 'SOFTWARE ENGINEERING I      ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '371', 'COMPUTER GRAPHICS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '490', 'COMPUTER SCIENCE PROJECT I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '492', 'COMPUTER SCIENCE PROJECT II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '100', 'COOP WORK TERM 1 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '200', 'COOP WORK TERM 2 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '300', 'COOP WORK TERM 3 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '400', 'COOP WORK TERM 4 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '100', 'COOP WORK TERM 1 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '200', 'COOP WORK TERM 2 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '300', 'COOP WORK TERM 3 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '400', 'COOP WORK TERM 4 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '251', 'FUNDMNTL/APPLI ELECTROMAGNET', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '264', 'SIGNALS AND SYSTEMS I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '275', 'PRINCIPLES OF ELEC. ENGG.   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '311', 'ELECTRONICS I               ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '364', 'SIGNALS AND SYSTEMS II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '370', 'MODEL+ANALYSIS/PHYS.SYSTEMS ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '425', 'OPT.DEV.  H S COMMUNICATIONS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '433', 'POWER ELECTRONICS           ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '442', 'DIGITAL SIGNAL PROCESSING   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '462', 'DIGITAL TRANSMISSION SYSTEMS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENCS', '272', 'COMP.& ARGUMENTATION FOR ENG', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENCS', '282', 'TECH. WRITING + COMMUNIC N. ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '390', 'CIVIL ENG. DESIGN PROJECT   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '469', 'GEO-ENVIRONMENTAL ENGINEER. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '244', 'PROGRAMMING METHODOLOGY II  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '312', 'DIGITAL SYSTEMS DESIGN      ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '352', 'DATA STRUCTURES & ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '107', 'COMP SCI INDUS EXPERIENCE I ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '207', 'COMP SCI INDUS EXPERIENCE II', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '228', 'SYSTEM HARDWARE             ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '233', 'PROB. & STATS. FOR COMP. SC.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '248', 'OBJ-ORIENTED PROGRAMMING I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '249', 'OBJ-ORIENTED PROGRAMMING II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '335', 'INTRO/THEORETICAL COMP SCI  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '346', 'OPERATING SYSTEMS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '348', 'PRIN./PROGRAMMING LANGUAGES ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '352', 'DATA STRUCTURES + ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '353', 'DATABASES                   ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '354', 'SOFTWARE ENGINEERING I      ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '371', 'COMPUTER GRAPHICS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '490', 'COMPUTER SCIENCE PROJECT I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '492', 'COMPUTER SCIENCE PROJECT II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '100', 'COOP WORK TERM 1 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '200', 'COOP WORK TERM 2 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '300', 'COOP WORK TERM 3 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '400', 'COOP WORK TERM 4 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '100', 'COOP WORK TERM 1 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '200', 'COOP WORK TERM 2 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '300', 'COOP WORK TERM 3 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '400', 'COOP WORK TERM 4 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '251', 'FUNDMNTL/APPLI ELECTROMAGNET', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '264', 'SIGNALS AND SYSTEMS I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '275', 'PRINCIPLES OF ELEC. ENGG.   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '311', 'ELECTRONICS I               ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '364', 'SIGNALS AND SYSTEMS II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '370', 'MODEL+ANALYSIS/PHYS.SYSTEMS ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '425', 'OPT.DEV.  H S COMMUNICATIONS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '433', 'POWER ELECTRONICS           ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '442', 'DIGITAL SIGNAL PROCESSING   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '462', 'DIGITAL TRANSMISSION SYSTEMS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENCS', '272', 'COMP.& ARGUMENTATION FOR ENG', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENCS', '282', 'TECH. WRITING + COMMUNIC N. ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '107', 'ENGR INDUS EXPERIENCE I     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '201', 'PROFESS L. PRACTICE+RESPONS.', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '202', 'SUSTAIN.DEV.+ENVIRO.STEWART.', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '207', 'ENGR INDUS EXPERIENCE II    ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '213', 'APP.ORDINARY DIFF.EQUATIONS ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '233', 'APPLIED ADVANCED CALCULUS   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '243', 'DYNAMICS                    ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '244', 'MECHANICS OF MATERIALS      ', '3.75');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '251', 'THERMODYNAMICS I            ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '301', 'ENGR.MGMT.PRINCIP.+ECONOMICS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '307', 'ENGR INDUS EXPERIENCE III   ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '311', 'TRANSF.CALC+PART.DIFF.EQNS  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '361', 'FLUID MECHANICS I           ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '371', 'PROBABILITY+STATISTICS/ENGR.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '391', 'NUMERICAL METHODS IN ENGR   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '392', 'IMPACT/TECHNOLOGY ON SOCIETY', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '410', 'TECHNICAL REPORT            ', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '411', 'SPECIAL TECHNICAL REPORT    ', '1');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '390', 'CIVIL ENG. DESIGN PROJECT   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '469', 'GEO-ENVIRONMENTAL ENGINEER. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '244', 'PROGRAMMING METHODOLOGY II  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '312', 'DIGITAL SYSTEMS DESIGN      ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '352', 'DATA STRUCTURES & ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '107', 'COMP SCI INDUS EXPERIENCE I ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '207', 'COMP SCI INDUS EXPERIENCE II', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '228', 'SYSTEM HARDWARE             ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '233', 'PROB. & STATS. FOR COMP. SC.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '248', 'OBJ-ORIENTED PROGRAMMING I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '249', 'OBJ-ORIENTED PROGRAMMING II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '335', 'INTRO/THEORETICAL COMP SCI  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '346', 'OPERATING SYSTEMS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '348', 'PRIN./PROGRAMMING LANGUAGES ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '352', 'DATA STRUCTURES + ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '353', 'DATABASES                   ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '354', 'SOFTWARE ENGINEERING I      ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '371', 'COMPUTER GRAPHICS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '490', 'COMPUTER SCIENCE PROJECT I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '492', 'COMPUTER SCIENCE PROJECT II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '100', 'COOP WORK TERM 1 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '200', 'COOP WORK TERM 2 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '300', 'COOP WORK TERM 3 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '400', 'COOP WORK TERM 4 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '100', 'COOP WORK TERM 1 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '200', 'COOP WORK TERM 2 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '300', 'COOP WORK TERM 3 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '400', 'COOP WORK TERM 4 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '251', 'FUNDMNTL/APPLI ELECTROMAGNET', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '264', 'SIGNALS AND SYSTEMS I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '275', 'PRINCIPLES OF ELEC. ENGG.   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '311', 'ELECTRONICS I               ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '364', 'SIGNALS AND SYSTEMS II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '370', 'MODEL+ANALYSIS/PHYS.SYSTEMS ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '425', 'OPT.DEV.  H S COMMUNICATIONS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '433', 'POWER ELECTRONICS           ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '442', 'DIGITAL SIGNAL PROCESSING   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '462', 'DIGITAL TRANSMISSION SYSTEMS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENCS', '272', 'COMP.& ARGUMENTATION FOR ENG', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENCS', '282', 'TECH. WRITING + COMMUNIC N. ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '107', 'ENGR INDUS EXPERIENCE I     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '201', 'PROFESS L. PRACTICE+RESPONS.', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '202', 'SUSTAIN.DEV.+ENVIRO.STEWART.', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '207', 'ENGR INDUS EXPERIENCE II    ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '213', 'APP.ORDINARY DIFF.EQUATIONS ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '233', 'APPLIED ADVANCED CALCULUS   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '243', 'DYNAMICS                    ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '244', 'MECHANICS OF MATERIALS      ', '3.75');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '251', 'THERMODYNAMICS I            ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '301', 'ENGR.MGMT.PRINCIP.+ECONOMICS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '307', 'ENGR INDUS EXPERIENCE III   ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '311', 'TRANSF.CALC+PART.DIFF.EQNS  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '361', 'FLUID MECHANICS I           ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '371', 'PROBABILITY+STATISTICS/ENGR.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '391', 'NUMERICAL METHODS IN ENGR   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '392', 'IMPACT/TECHNOLOGY ON SOCIETY', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '410', 'TECHNICAL REPORT            ', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '411', 'SPECIAL TECHNICAL REPORT    ', '1');
insert into Course(DepartmentId, Number, Name, Credits) values('IADI', '301', 'U/G AEROSPACE INDUS Y PROJ 1', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('IADI', '401', 'U/G AEROSPACE INDUS Y PROJ 2', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '390', 'CIVIL ENG. DESIGN PROJECT   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '469', 'GEO-ENVIRONMENTAL ENGINEER. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '244', 'PROGRAMMING METHODOLOGY II  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '312', 'DIGITAL SYSTEMS DESIGN      ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '352', 'DATA STRUCTURES & ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '107', 'COMP SCI INDUS EXPERIENCE I ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '207', 'COMP SCI INDUS EXPERIENCE II', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '228', 'SYSTEM HARDWARE             ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '233', 'PROB. & STATS. FOR COMP. SC.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '248', 'OBJ-ORIENTED PROGRAMMING I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '249', 'OBJ-ORIENTED PROGRAMMING II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '335', 'INTRO/THEORETICAL COMP SCI  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '346', 'OPERATING SYSTEMS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '348', 'PRIN./PROGRAMMING LANGUAGES ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '352', 'DATA STRUCTURES + ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '353', 'DATABASES                   ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '354', 'SOFTWARE ENGINEERING I      ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '371', 'COMPUTER GRAPHICS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '490', 'COMPUTER SCIENCE PROJECT I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '492', 'COMPUTER SCIENCE PROJECT II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '100', 'COOP WORK TERM 1 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '200', 'COOP WORK TERM 2 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '300', 'COOP WORK TERM 3 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '400', 'COOP WORK TERM 4 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '100', 'COOP WORK TERM 1 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '200', 'COOP WORK TERM 2 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '300', 'COOP WORK TERM 3 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '400', 'COOP WORK TERM 4 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '251', 'FUNDMNTL/APPLI ELECTROMAGNET', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '264', 'SIGNALS AND SYSTEMS I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '275', 'PRINCIPLES OF ELEC. ENGG.   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '311', 'ELECTRONICS I               ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '364', 'SIGNALS AND SYSTEMS II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '370', 'MODEL+ANALYSIS/PHYS.SYSTEMS ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '425', 'OPT.DEV.  H S COMMUNICATIONS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '433', 'POWER ELECTRONICS           ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '442', 'DIGITAL SIGNAL PROCESSING   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '462', 'DIGITAL TRANSMISSION SYSTEMS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENCS', '272', 'COMP.& ARGUMENTATION FOR ENG', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENCS', '282', 'TECH. WRITING + COMMUNIC N. ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '107', 'ENGR INDUS EXPERIENCE I     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '201', 'PROFESS L. PRACTICE+RESPONS.', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '202', 'SUSTAIN.DEV.+ENVIRO.STEWART.', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '207', 'ENGR INDUS EXPERIENCE II    ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '213', 'APP.ORDINARY DIFF.EQUATIONS ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '233', 'APPLIED ADVANCED CALCULUS   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '243', 'DYNAMICS                    ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '244', 'MECHANICS OF MATERIALS      ', '3.75');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '251', 'THERMODYNAMICS I            ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '301', 'ENGR.MGMT.PRINCIP.+ECONOMICS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '307', 'ENGR INDUS EXPERIENCE III   ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '311', 'TRANSF.CALC+PART.DIFF.EQNS  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '361', 'FLUID MECHANICS I           ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '371', 'PROBABILITY+STATISTICS/ENGR.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '391', 'NUMERICAL METHODS IN ENGR   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '392', 'IMPACT/TECHNOLOGY ON SOCIETY', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '410', 'TECHNICAL REPORT            ', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '411', 'SPECIAL TECHNICAL REPORT    ', '1');
insert into Course(DepartmentId, Number, Name, Credits) values('IADI', '301', 'U/G AEROSPACE INDUS Y PROJ 1', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('IADI', '401', 'U/G AEROSPACE INDUS Y PROJ 2', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '390', 'CIVIL ENG. DESIGN PROJECT   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '469', 'GEO-ENVIRONMENTAL ENGINEER. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '244', 'PROGRAMMING METHODOLOGY II  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '312', 'DIGITAL SYSTEMS DESIGN      ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '352', 'DATA STRUCTURES & ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '107', 'COMP SCI INDUS EXPERIENCE I ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '207', 'COMP SCI INDUS EXPERIENCE II', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '228', 'SYSTEM HARDWARE             ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '233', 'PROB. & STATS. FOR COMP. SC.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '248', 'OBJ-ORIENTED PROGRAMMING I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '249', 'OBJ-ORIENTED PROGRAMMING II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '335', 'INTRO/THEORETICAL COMP SCI  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '346', 'OPERATING SYSTEMS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '348', 'PRIN./PROGRAMMING LANGUAGES ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '352', 'DATA STRUCTURES + ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '353', 'DATABASES                   ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '354', 'SOFTWARE ENGINEERING I      ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '371', 'COMPUTER GRAPHICS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '490', 'COMPUTER SCIENCE PROJECT I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '492', 'COMPUTER SCIENCE PROJECT II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '100', 'COOP WORK TERM 1 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '200', 'COOP WORK TERM 2 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '300', 'COOP WORK TERM 3 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '400', 'COOP WORK TERM 4 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '100', 'COOP WORK TERM 1 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '200', 'COOP WORK TERM 2 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '300', 'COOP WORK TERM 3 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '400', 'COOP WORK TERM 4 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '251', 'FUNDMNTL/APPLI ELECTROMAGNET', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '264', 'SIGNALS AND SYSTEMS I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '275', 'PRINCIPLES OF ELEC. ENGG.   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '311', 'ELECTRONICS I               ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '364', 'SIGNALS AND SYSTEMS II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '370', 'MODEL+ANALYSIS/PHYS.SYSTEMS ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '425', 'OPT.DEV.  H S COMMUNICATIONS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '433', 'POWER ELECTRONICS           ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '442', 'DIGITAL SIGNAL PROCESSING   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '462', 'DIGITAL TRANSMISSION SYSTEMS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENCS', '272', 'COMP.& ARGUMENTATION FOR ENG', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENCS', '282', 'TECH. WRITING + COMMUNIC N. ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '107', 'ENGR INDUS EXPERIENCE I     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '201', 'PROFESS L. PRACTICE+RESPONS.', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '202', 'SUSTAIN.DEV.+ENVIRO.STEWART.', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '207', 'ENGR INDUS EXPERIENCE II    ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '213', 'APP.ORDINARY DIFF.EQUATIONS ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '233', 'APPLIED ADVANCED CALCULUS   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '243', 'DYNAMICS                    ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '244', 'MECHANICS OF MATERIALS      ', '3.75');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '251', 'THERMODYNAMICS I            ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '301', 'ENGR.MGMT.PRINCIP.+ECONOMICS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '307', 'ENGR INDUS EXPERIENCE III   ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '311', 'TRANSF.CALC+PART.DIFF.EQNS  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '361', 'FLUID MECHANICS I           ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '371', 'PROBABILITY+STATISTICS/ENGR.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '391', 'NUMERICAL METHODS IN ENGR   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '392', 'IMPACT/TECHNOLOGY ON SOCIETY', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '410', 'TECHNICAL REPORT            ', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '411', 'SPECIAL TECHNICAL REPORT    ', '1');
insert into Course(DepartmentId, Number, Name, Credits) values('IADI', '301', 'U/G AEROSPACE INDUS Y PROJ 1', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('IADI', '401', 'U/G AEROSPACE INDUS Y PROJ 2', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('MECH', '311', 'MANUFACTURING PROCESSES     ', '3.75');
insert into Course(DepartmentId, Number, Name, Credits) values('MECH', '313', 'MACHINE DRAWING + DESIGN    ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('MECH', '343', 'THEORY OF MACHINES I        ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('MECH', '370', 'MODELLING, SIM. & CONT SYS. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '342', 'STRUCTURAL ANALYSIS I       ', '2');
insert into Course(DepartmentId, Number, Name, Credits) values('BCEE', '371', 'SURVEYING                   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '390', 'BUILDING ENG. DESIGN PROJECT', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('BLDG', '473', 'BUILDING ACOUSTICS          ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '390', 'CIVIL ENG. DESIGN PROJECT   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('CIVI', '469', 'GEO-ENVIRONMENTAL ENGINEER. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '244', 'PROGRAMMING METHODOLOGY II  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '312', 'DIGITAL SYSTEMS DESIGN      ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('COEN', '352', 'DATA STRUCTURES & ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '107', 'COMP SCI INDUS EXPERIENCE I ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '207', 'COMP SCI INDUS EXPERIENCE II', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '228', 'SYSTEM HARDWARE             ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '233', 'PROB. & STATS. FOR COMP. SC.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '248', 'OBJ-ORIENTED PROGRAMMING I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '249', 'OBJ-ORIENTED PROGRAMMING II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '335', 'INTRO/THEORETICAL COMP SCI  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '346', 'OPERATING SYSTEMS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '348', 'PRIN./PROGRAMMING LANGUAGES ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '352', 'DATA STRUCTURES + ALGORITHMS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '353', 'DATABASES                   ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '354', 'SOFTWARE ENGINEERING I      ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '371', 'COMPUTER GRAPHICS           ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '490', 'COMPUTER SCIENCE PROJECT I  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('COMP', '492', 'COMPUTER SCIENCE PROJECT II ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '100', 'COOP WORK TERM 1 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '200', 'COOP WORK TERM 2 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '300', 'COOP WORK TERM 3 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '400', 'COOP WORK TERM 4 (COMP)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTC', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '100', 'COOP WORK TERM 1 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '101', 'REFLECTIVE LEARNING I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '200', 'COOP WORK TERM 2 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '201', 'REFLECTIVE LEARNING II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '300', 'COOP WORK TERM 3 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '301', 'REFLECTIVE LEARNING III     ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '400', 'COOP WORK TERM 4 (ENGR)     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('CWTE', '401', 'REFLECTIVE LEARNING IV      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '251', 'FUNDMNTL/APPLI ELECTROMAGNET', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '264', 'SIGNALS AND SYSTEMS I       ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '275', 'PRINCIPLES OF ELEC. ENGG.   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '311', 'ELECTRONICS I               ', '4');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '364', 'SIGNALS AND SYSTEMS II      ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '370', 'MODEL+ANALYSIS/PHYS.SYSTEMS ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '425', 'OPT.DEV.  H S COMMUNICATIONS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '433', 'POWER ELECTRONICS           ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '442', 'DIGITAL SIGNAL PROCESSING   ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ELEC', '462', 'DIGITAL TRANSMISSION SYSTEMS', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENCS', '272', 'COMP.& ARGUMENTATION FOR ENG', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENCS', '282', 'TECH. WRITING + COMMUNIC N. ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '107', 'ENGR INDUS EXPERIENCE I     ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '201', 'PROFESS L. PRACTICE+RESPONS.', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '202', 'SUSTAIN.DEV.+ENVIRO.STEWART.', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '207', 'ENGR INDUS EXPERIENCE II    ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '213', 'APP.ORDINARY DIFF.EQUATIONS ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '233', 'APPLIED ADVANCED CALCULUS   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '243', 'DYNAMICS                    ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '244', 'MECHANICS OF MATERIALS      ', '3.75');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '251', 'THERMODYNAMICS I            ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '301', 'ENGR.MGMT.PRINCIP.+ECONOMICS', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '307', 'ENGR INDUS EXPERIENCE III   ', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '311', 'TRANSF.CALC+PART.DIFF.EQNS  ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '361', 'FLUID MECHANICS I           ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '371', 'PROBABILITY+STATISTICS/ENGR.', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '391', 'NUMERICAL METHODS IN ENGR   ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '392', 'IMPACT/TECHNOLOGY ON SOCIETY', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '410', 'TECHNICAL REPORT            ', '1.5');
insert into Course(DepartmentId, Number, Name, Credits) values('ENGR', '411', 'SPECIAL TECHNICAL REPORT    ', '1');
insert into Course(DepartmentId, Number, Name, Credits) values('IADI', '301', 'U/G AEROSPACE INDUS Y PROJ 1', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('IADI', '401', 'U/G AEROSPACE INDUS Y PROJ 2', '0');
insert into Course(DepartmentId, Number, Name, Credits) values('MECH', '311', 'MANUFACTURING PROCESSES     ', '3.75');
insert into Course(DepartmentId, Number, Name, Credits) values('MECH', '313', 'MACHINE DRAWING + DESIGN    ', '3');
insert into Course(DepartmentId, Number, Name, Credits) values('MECH', '343', 'THEORY OF MACHINES I        ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('MECH', '370', 'MODELLING, SIM. & CONT SYS. ', '3.5');
insert into Course(DepartmentId, Number, Name, Credits) values('SOEN', '287', 'INTRO. TO WEB APPLICATIONS  ', '3');
