delete from RegisteredIn;
delete from StudentProgram;
delete from SequenceDetails;
delete from Program where not Name='DERP';
delete from Satisfies;
delete from Requires;
delete from ClassBlock;
delete from Class;
delete from Course where not DepartmentID='DERP';
delete from Department where not DepartmentID='DERP';
delete from Faculty where not FacultyID='DERP';
